"""Numerical parity tests against R openair.

These tests assert that aeolus metrics produce numerically identical output
to R openair for the same input. Reference outputs are pre-generated by
``scripts/validation/generate_openair_fixtures.R`` and checked into
``tests/fixtures/openair/``. You do not need R installed to run these tests.

The comparison pattern is deliberately conservative:
1. Load raw AURN data that openair produced (same bytes, same upstream source)
2. Convert that raw wide-format DataFrame to the aeolus long-format schema
3. Run the aeolus metric
4. Reshape aeolus output back to wide format
5. Assert value-by-value equivalence to the openair reference

This isolates metric-computation parity from data-loading differences. If
aeolus.download() and openair.importAURN() produced different raw data, that
would be a separate (and legitimate) bug — but it's not what this test file
is checking.

See ``docs/validation/openair-parity.qmd`` for the user-facing narrative
comparison rendered from this same fixture data.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from aeolus.metrics import time_average


FIXTURES = Path(__file__).parent / "fixtures" / "openair"


# ============================================================================
# Fixture loaders
# ============================================================================


def _read_openair_csv(path: Path) -> pd.DataFrame:
    """Read an openair-generated CSV with UTC-aware ``date`` column."""
    df = pd.read_csv(path)
    df["date"] = pd.to_datetime(df["date"], utc=True)
    return df


@pytest.fixture(scope="module")
def raw_wide():
    """Hourly AURN data in openair's native wide format (one column per
    pollutant). Produced by ``importAURN('my1', 2023)``."""
    return _read_openair_csv(FIXTURES / "aurn_my1_2023_raw.csv")


@pytest.fixture(scope="module")
def openair_daily_mean():
    """Daily mean from ``openair::timeAverage(avg.time='day', data.thresh=75)``."""
    return _read_openair_csv(FIXTURES / "aurn_my1_2023_daily_mean_thresh75.csv")


@pytest.fixture(scope="module")
def raw_long(raw_wide):
    """raw_wide reshaped into aeolus's 8-column long-format schema."""
    pollutant_cols = [c for c in raw_wide.columns if c not in ("date", "site", "code")]
    long = raw_wide.melt(
        id_vars=["date", "site", "code"],
        value_vars=pollutant_cols,
        var_name="measurand",
        value_name="value",
    )
    # Canonicalise pollutant names: openair emits lowercase "no2", "pm2.5", etc.
    measurand_map = {"no2": "NO2", "pm2.5": "PM2.5", "pm10": "PM10", "o3": "O3"}
    long["measurand"] = long["measurand"].map(measurand_map)

    out = pd.DataFrame({
        "site_code": long["code"],
        "date_time": long["date"],
        "measurand": long["measurand"],
        "value": pd.to_numeric(long["value"], errors="coerce"),
        "units": "ug/m3",
        "source_network": "AURN",
        "ratification": "None",
        "created_at": datetime(2024, 1, 1, tzinfo=timezone.utc),
    })
    return out


# ============================================================================
# Parity tests
# ============================================================================


def _pivot_aeolus_to_wide(df: pd.DataFrame) -> pd.DataFrame:
    """Reshape aeolus long-format output into openair-style wide format."""
    wide = df.pivot_table(
        index="date_time",
        columns="measurand",
        values="value",
        aggfunc="first",  # after time_average there's one value per cell
    )
    wide = wide.reset_index().rename(columns={"date_time": "date"})
    # Map aeolus measurand names back to openair's lowercase form
    rename = {"NO2": "no2", "PM2.5": "pm2.5", "PM10": "pm10", "O3": "o3"}
    wide = wide.rename(columns=rename)
    return wide


def _assert_wide_frames_match(
    aeolus_wide: pd.DataFrame,
    openair_wide: pd.DataFrame,
    pollutants: list[str],
    atol: float = 1e-12,
) -> None:
    """Tolerance is set at 1e-12 ug/m3 — eight orders of magnitude below any
    physically meaningful measurement. Observed max diff is ~5e-14, so this
    leaves margin for floating-point order-of-operations drift but would
    catch any real algorithmic divergence."""
    """Compare wide-format DataFrames, aligned on date. Fail with a diff table."""
    # Align on date
    merged = aeolus_wide.merge(
        openair_wide, on="date", how="outer", suffixes=("_aeolus", "_openair")
    )

    for p in pollutants:
        a_col = f"{p}_aeolus"
        o_col = f"{p}_openair"
        if a_col not in merged.columns or o_col not in merged.columns:
            pytest.fail(f"Missing comparison column for {p}: {a_col}/{o_col}")

        a = merged[a_col].to_numpy()
        o = merged[o_col].to_numpy()

        # Both NaN in the same places — openair and aeolus agree on coverage
        a_nan = np.isnan(a)
        o_nan = np.isnan(o)
        nan_mismatch = (a_nan != o_nan).sum()
        assert nan_mismatch == 0, (
            f"{p}: {nan_mismatch} rows have NaN in one frame but not the other. "
            f"Likely a data-capture threshold mismatch."
        )

        # Compare non-NaN values
        both_valid = ~a_nan & ~o_nan
        diffs = np.abs(a[both_valid] - o[both_valid])
        max_diff = diffs.max() if len(diffs) else 0.0
        n_beyond_tol = (diffs > atol).sum()

        assert n_beyond_tol == 0, (
            f"{p}: {n_beyond_tol}/{both_valid.sum()} rows differ by more "
            f"than {atol} ug/m3. Max diff: {max_diff:g}."
        )


class TestTimeAverageDailyMean:
    """aeolus.time_average(freq='D', data_thresh=0.75) must match
    openair::timeAverage(avg.time='day', data.thresh=75)."""

    def test_daily_mean_matches_openair(self, raw_long, openair_daily_mean):
        aeolus_daily = time_average(raw_long, freq="D", data_thresh=0.75)
        aeolus_wide = _pivot_aeolus_to_wide(aeolus_daily)
        _assert_wide_frames_match(
            aeolus_wide,
            openair_daily_mean,
            pollutants=["no2", "pm2.5", "pm10", "o3"],
        )

    def test_row_count_matches(self, raw_long, openair_daily_mean):
        """Both should emit one row per day regardless of data capture — a
        day below threshold becomes NaN, not absent."""
        aeolus_daily = time_average(raw_long, freq="D", data_thresh=0.75)
        unique_days = aeolus_daily["date_time"].dt.normalize().nunique()
        assert unique_days == len(openair_daily_mean), (
            f"aeolus produced {unique_days} days, openair produced "
            f"{len(openair_daily_mean)}"
        )


# ============================================================================
# Provenance display — surfaced in pytest verbose output
# ============================================================================


def test_fixture_provenance_is_documented():
    """A provenance file must exist alongside the data fixtures so readers
    can see which openair version produced them."""
    provenance_path = FIXTURES / "provenance.csv"
    assert provenance_path.exists(), (
        "Missing provenance.csv — regenerate fixtures with "
        "scripts/validation/generate_openair_fixtures.R"
    )
    prov = pd.read_csv(provenance_path)
    assert "openair_version" in prov.columns
    assert not prov.empty
